export const GET_QUESTIONS_REQUEST = "GET_QUESTIONS_REQUEST";
export const GET_QUESTIONS_SUCCESS = "GET_QUESTIONS_SUCCESS";
export const GET_QUESTIONS_FAILURE = "GET_QUESTIONS_FAILURE";

export const FIND_QUESTION_BY_ID_REQUEST = "FIND_QUESTION_BY_ID_REQUEST";
export const FIND_QUESTION_BY_ID_SUCCESS = "FIND_QUESTION_BY_ID_SUCCESS";
export const FIND_QUESTION_BY_ID_FAILURE = "FIND_QUESTION_BY_ID_FAILURE";

export const CREATE_QUESTION_REQUEST = "CREATE_QUESTION_REQUEST";
export const CREATE_QUESTION_SUCCESS = "CREATE_QUESTION_SUCCESS";
export const CREATE_QUESTION_FAILURE = "CREATE_QUESTION_FAILURE";

export const CREATE_ANSWER_REQUEST = "CREATE_ANSWER_REQUEST";
export const CREATE_ANSWER_SUCCESS = "CREATE_ANSWER_SUCCESS";
export const CREATE_ANSWER_FAILURE = "CREATE_ANSWER_FAILURE";

export const CREATE_QUESTION_UPVOTE_REQUEST = "CREATE_QUESTION_UPVOTE_REQUEST";
export const CREATE_QUESTION_UPVOTE_SUCCESS = "CREATE_QUESTION_UPVOTE_SUCCESS";
export const CREATE_QUESTION_UPVOTE_FAILURE = "CREATE_QUESTION_UPVOTE_FAILURE";

export const CREATE_ANSWER_UPVOTE_REQUEST = "CREATE_ANSWER_UPVOTE_REQUEST";
export const CREATE_ANSWER_UPVOTE_SUCCESS = "CREATE_ANSWER_UPVOTE_SUCCESS";
export const CREATE_ANSWER_UPVOTE_FAILURE = "CREATE_ANSWER_UPVOTE_FAILURE";

export const DESTROY_QUESTION_UPVOTE_REQUEST =
  "DESTROY_QUESTION_UPVOTE_REQUEST";
export const DESTROY_QUESTION_UPVOTE_SUCCESS =
  "DESTROY_QUESTION_UPVOTE_SUCCESS";
export const DESTROY_QUESTION_UPVOTE_FAILURE =
  "DESTROY_QUESTION_UPVOTE_FAILURE";

export const DESTROY_ANSWER_UPVOTE_REQUEST = "DESTROY_ANSWER_UPVOTE_REQUEST";
export const DESTROY_ANSWER_UPVOTE_SUCCESS = "DESTROY_ANSWER_UPVOTE_SUCCESS";
export const DESTROY_ANSWER_UPVOTE_FAILURE = "DESTROY_ANSWER_UPVOTE_FAILURE";
