export const CREATE_QUESTION_COMMENT_REQUEST =
  "CREATE_QUESTION_COMMENT_REQUEST";
export const CREATE_QUESTION_COMMENT_SUCCESS =
  "CREATE_QUESTION_COMMENT_SUCCESS";
export const CREATE_QUESTION_COMMENT_FAILURE =
  "CREATE_QUESTION_COMMENT_FAILURE";

export const CREATE_ANSWER_COMMENT_REQUEST = "CREATE_ANSWER_COMMENT_REQUEST";
export const CREATE_ANSWER_COMMENT_SUCCESS = "CREATE_ANSWER_COMMENT_SUCCESS";
export const CREATE_ANSWER_COMMENT_FAILURE = "CREATE_ANSWER_COMMENT_FAILURE";
